### ISSUE TITLE
Colour switching not working in Plasma 6

### ISSUE THREAD

**Issue by ElHyperion** [eritbh/kde-application-titlebar-themes#1]
I've followed your instructions and verified that my apps are matched correctly, but the colours aren't changing. Even if I switch to some of the default themes (I currently use Otto). Has anyone managed to get it working on Plasma 6?

**Comment by eritbh** [comment]
I can't say I'm having any issues on my machines. I don't have a machine with a fresh Plasma 6 install to test with, but my desktop was upgraded from 5 to 6; all its existing settings were preserved, and I can apply color schemes to new applications in the same way as before. Can't say I know why you're having problems...

![image](https://github.com/user-attachments/assets/25af555b-e1be-4c28-a88c-5ce796123366)

**Comment by ElHyperion** [comment]
I alredy figured the problem out - this only works with Breeze window decorations 🙁. I was in the process of theming my Plasma and this was one of the finishing touches, after I had already enabled Aurorae window decorations.

I suppose it would be a good idea to mention it in the readme to save others' time.

**Comment by eritbh** [comment]
Interesting, I wasn't aware of this limitation! I've found some additional information about that in [this forum thread](https://discuss.kde.org/t/titlebar-color-change/17231/14) and I'll add a note to the README about it, thanks.
